# Basic
title: JC
subtitle: 不以物喜,不以己悲
welcome_message: 一个低调的iOS程序猿
description: An unobtrusive programmer.
creator: <a href="https://baixiaohui.github.io/jc.github.io/">@onevcat</a>

url: "https://baixiaohui.github.io/jc.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'https://baixiaohui.github.io/jc.github.io/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: JC
    # duoshuo: 
    
# Social
social:
    weibo: 2737627267
    github: baixiaohui
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: lowkeyprogrammer@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
